title: Saebyn's Blog
description: Various ramblings about my work and what I'm thinking about.
disqus_shortname: saebyn
reading_time: true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://saebyn.info

# Owner/author information
owner:
  name: Saebyn
  avatar: avatar.jpg
  bio: "I like solving problems, building systems, learning new things, and exploring the works of others."
  email: saebynx@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: saebyn
  facebook:
  github: https://github.com/saebyn
  stackexchange: http://stackoverflow.com/users/123383/saebyn
  linkedin: saebynx
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-6365132-2
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Vancouver
future: false # publish future dated posts --  true, false (default)
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-mermaid
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: pretty

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
